GNU := http://ftp.gnu.org

lynx-2.8.2rel.1:
	wget https://invisible-mirror.net/archives/lynx/tarballs/lynx2.8.2rel.1.tar.gz

gcc-2.8.1.tar.gz:
	wget $(GNU)/gnu/gcc/gcc-2.8.1.tar.gz

glibc-2.1.2.tar.gz:
	wget $(GNU)/gnu/libc/glibc-2.1.2.tar.gz

links-2.22.tar.gz:
	wget http://links.twibright.com/download/$@

links-2.25.tar.gz:
	wget http://links.twibright.com/download/links-2.25.tar.gz
