#! /usr/local/bin/bash
name=pkgconfig
version=0.9.0

folder=$name-$version
tarball=backstep/warehouse/$folder.tar.gz
PREFIX=/opt/backstep

if [ ! -d $folder ]
then
	gzip -dc $tarball | tar xf -
fi

cd $folder
CC=cc ./configure --prefix $PREFIX && make
cd ..
