#! /bin/sh
# Invoke this from the parent build directory.

# Phase 0: packages required before any other builds.

backstep/uname/build
backstep/patch-2.5.4/build
backstep/pkgconfig-0.3.0/build
backstep/wget-1.4.5/build

