#! /bin/sh
# Invoke this from the parent install directory.

# Phase 0: packages required to build most anything.

backstep/uname/install
backstep/patch-2.5.4/install
backstep/pkgconfig-0.3.0/install

