#! /bin/sh
# Invoke this from the parent install directory.

# Phase 0: packages required to build most anything.

BaCKSTEP/uname/install
BaCKSTEP/patch-2.5.4/install
BaCKSTEP/pkgconfig-0.3.0/install

