#! /bin/sh
# Invoke this from the parent build directory.

# Phase 2: packages dependent on Phase 1 packages.

backstep/automake-1.4-p6/build
backstep/autoconf-2.13/build
backstep/gcc-2.95.3/build
backstep/glib-1.2.8/build
backstep/links-2.1pre19/build

