#! /bin/sh
# Invoke this from the parent install directory.

# Phase 2: packages dependent on built packages.

backstep/automake-1.4-p6/install
backstep/autoconf-2.13/install

# Last packages before Phase 2.
backstep/gcc-2.95.3/install
backstep/make-3.75/install
