#! /bin/sh
# Invoke this from the parent install directory.

# Phase 2: packages dependent on built packages.

BaCKSTEP/automake-1.4-p6/install
BaCKSTEP/autoconf-2.13/install

# Last packages before Phase 2.
BaCKSTEP/gcc-2.95.3/install
BaCKSTEP/make-3.75/install
