#! /bin/sh
# Copy into the package dir, set variables, and chmod +x.

name=name
version=version

gzip -dc backstep/warehouse/$name-$version.tar.gz | tar xf -
cd $name-$version
./configure && make

# additional configure options
#--prefix=$HOME/Unix
#--build m68k-next-nextstep3
