#! /bin/sh

# Phase 1: packages that build with the NS3.3 toolchain.

## Shell upgrades.

BaCKSTEP/bash-2.0/build
BaCKSTEP/sh-utils-1.16/build
BaCKSTEP/fileutils-3.16/build
BaCKSTEP/textutils-1.22/build

## Toolchain upgrades.

BaCKSTEP/m4-1.4.1/build
#BaCKSTEP/perl5-004_05/build


# Phase 2: packages dependent on built packages.

#BaCKSTEP/automake-1.4-p6/build
#BaCKSTEP/autoconf-2.13/build

# Last packages before Phase 2.
#BaCKSTEP/gcc-2.95.3/build
#BaCKSTEP/make-3.75/build

