#! /bin/sh
# Copy into the package dir, set variables, and chmod +x.

name=name
version=version

folder=$name-$version
tarball=backstep/warehouse/$name-$version.tar.gz

if [ ! -d $name-$version ]
then
	gzip -dc $tarball | tar xf -
fi

cd $name-$version
./configure && make

# additional configure options
#--prefix=$HOME/Unix
#--build m68k-next-nextstep3
