#! /bin/sh
name=expat
version=2.1.0

. env
PATH=$PREFIX/bin:$PATH
CC=cc

_configure() {
  if [ ! -d $name-$version ]
  then
    gnutar xzf backstep/warehouse/$name-$version.tar.Z
  fi
  cd $name-$version
  ./configure --prefix $PREFIX
  cd ..
}

_build() {
  cd $name-$version
  make
  cd ..
}

_install() {
  cd $name-$version
  make install
  cd ..
}

case $1 in
  configure)
  _configure
  ;;

  build)
  _build
  ;;

  install)
  _install
  ;;

  all)
  _configure && _build && _install
  ;;

esac

