#! /bin/sh
name=expat
version=2.1.0

PREFIX=/opt/backstep
PATH=$PREFIX/bin:$PATH
CC=cc

echo $PATH
exit

_configure() {
  if [ ! -d $name-$version ]
  then
    gzip -dc backstep/warehouse/$name-$version.tar.gz | tar xvf -
  fi
  cd $name-$version
  ./configure --prefix $PREFIX
  cd ..
}

_build() {
  cd $name-$version
  make
  cd ..
}

_install() {
  cd $name-$version
  make install
  cd ..
}

case $1 in
  configure)
  _configure
  ;;

  build)
  _build
  ;;

  install)
  _install
  ;;

  all)
  _configure && _build && _install
  ;;

esac

