#! /bin/sh
. env
name=sh-utils
version=1.16
tarball=$name-$version.tar.gz
url=http://ftp.gnu.org/pub/old-gnu/$name/$tarball

#(cd backstep/warehouse && wget $url)
gzip -dc backstep/warehouse/$name-$version.tar.gz | tar xf -
cd $name-$version
CC=cc ./configure --prefix $PREFIX
