#! /bin/sh
name=m4
version=1.4.1

PREFIX=/opt/backstep
#PATH=$PREFIX/bin:$PATH
#export PATH

case $1 in
  configure)
  if [ ! -d $name-$version ]
  then
    gzip -dc backstep/warehouse/$name-$version.tar.gz | tar xvf -
  fi
  cd $name-$version
  ./configure --prefix $PREFIX
  ;;

  build)
  cd $name-$version
  make
  ;;

  install)
  cd $name-$version
  make install
  ;;
esac
