#! /bin/sh

name=gcc
version=2.95.3
PREFIX=/usr/local

package=BaCKSTEP/warehouse/$name-$version.tar.gz
#gzip -dc $tarball | tar xf -

#cd $name-$version

#patch -p1 < ../BaCKSTEP/warehouse/gcc-2.95.3.patch

#CC=cc ./configure --enable-languages='c,objc' --disable-shared --disable-threads --enable-cpp

/bin/make CFLAGS='-O' LIBCFLAGS='-g -O2' LIBCXXFLAGS='-g -O2 -fno-implicit-templates' bootstrap

/bin/make install

#cd $PREFIX/lib/gcc-lib/m68k-next-nextstep3/2.95.3
#patch -p0 < BaCKSTEP/warehouse/gcc.2.95.3.specs.patch

